# https://asynchronous.in/docker-mailman/

version: '2'

services:

  #---------------------------------------------
  # NGINX -
  #---------------------------------------------
  nginx:
    image: nginx:latest
    container_name: nginx
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - 80:80
      - 443:443
    networks:
      mailman:

  #---------------------------------------------
  # MAILMAN - CORE
  #---------------------------------------------
  mailman-core:
    image: maxking/mailman-core:0.3
    container_name: mailman-core
    hostname: mailman-core
    volumes:
    - /opt/mailman/core:/opt/mailman/
    stop_grace_period: 30s
    links:
    - database:database
    depends_on:
    - database
    environment:
    # https://docs.mailman3.org/projects/mailman/en/latest/src/mailman/docs/database.html
    - DATABASE_URL=postgres://mailman:mailmanpass@database/mailmandb
    - DATABASE_TYPE=postgres
    - DATABASE_CLASS=mailman.database.postgresql.PostgreSQLDatabase
    - HYPERKITTY_API_KEY=someapikey
    ports:
    - "127.0.0.1:8001:8001" # API
    - "127.0.0.1:8024:8024" # LMTP - incoming emails
    networks:
      mailman:

  #---------------------------------------------
  # MAILMAN - WEB
  #---------------------------------------------
  mailman-web:
    image: maxking/mailman-web:0.3
    container_name: mailman-web
    hostname: mailman-web
    depends_on:
    - database
    links:
    - mailman-core:mailman-core
    - database:database
    volumes:
    - /opt/mailman/web:/opt/mailman-web-data
    environment:
    - DATABASE_TYPE=postgres
    - DATABASE_URL=postgres://mailman:mailmanpass@database/mailmandb
    - HYPERKITTY_API_KEY=someapikey
    - SERVE_FROM_DOMAIN=mailman.derekzoladz.com
    - MAILMAN_ADMIN_USER=admin
    - MAILMAN_ADMIN_EMAIL=admin@example.com
    - SECRET_KEY=75ntiw47heghfcitgeicgny
    - UWSGI_STATIC_MAP=/static=/opt/mailman-web-data/static
    # ---------------------------
    # DEFAULTS MADE EXPLICIT, REST API
    # ---------------------------
    - MAILMAN_REST_URL=http://mailman-core:8001 # Default = http://mailman-core:8001
    - MAILMAN_REST_USER=restadmin # Default = restadmin
    - MAILMAN_REST_PASSWORD=restpass # Default = restpass
    - MAILMAN_HOSTNAME=mailman-core # Default = mailman-core
    # ---------------------------
    # DEFAULTS MADE EXPLICIT, SMTP
    # IP Address/hostname from which you will be sending emails
    # ---------------------------
    #SMTP_HOST=  # Default value is the container's gateway retrieved from: /sbin/ip route | awk '/default/ { print $3 }'
    - SMTP_PORT=25 # Default = 25
    - SMTP_HOST_USER= # Default = empty string
    - SMTP_HOST_PASSWORD= # Default = empty string
    - SMTP_USE_TLS=False # Default = False
    - SMTP_USE_SSL=False # Default = False
    #ports:
    #- "127.0.0.1:8000:8000" # HTTP
    #- "127.0.0.1:8080:8080" # uwsgi
    expose:
      - 8000
      - 8080
    networks:
      mailman:

  #---------------------------------------------
  # POSTGRES DATABASE
  #---------------------------------------------
  database:
    environment:
    - POSTGRES_DB=mailmandb
    - POSTGRES_USER=mailman
    - POSTGRES_PASSWORD=mailmanpass
    image: postgres:9.6-alpine
    volumes:
    - /opt/mailman/database:/var/lib/postgresql/data
    networks:
      mailman:

networks:
  mailman:
    driver: bridge
    ipam:
      driver: default
      config:
      -
        subnet: 172.19.199.0/24